baseURL = 'https://portfolio.mileshilliard.com'
locale = 'en-us'
title = 'Miles Hilliard _'
theme = 'newsroom'

[params]
  faviconsDir = "images/icons/" # with a trailing slash

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
